### ISSUE TITLE
@js behaviour changes after `loadurl`

### ISSUE THREAD

**Issue by hhaensel** [JuliaGizmos/Blink.jl#156] opened 2018-09-27 00:19 UTC
After initialising a Blink window, the @js macro works just fine, but after loading a url, the answer is different and unusable. Any ideas? (I'm working on Julia 1.0.0 on Windows)

```julia
julia> using Blink
julia> w = Window();
julia> @js w Math.log(10)
2.302585092994046
julia> loadurl(w,"https://heise.de")
false
julia> @js w Math.log(10)
Dict{String,Any} with 0 entries
```

**Comment by NHDaly** [comment] 2019-08-22 13:52
I am closing this as a duplicate of https://github.com/JuliaGizmos/Blink.jl/issues/150: `loadurl` currently completely replaces the page, clobbering the all the javascript needed for proper communication with Blink.

**Closed by NHDaly** 2019-08-22 13:52 UTC
